language: python
python:
  - "2.7"
install: 
  - pip install -r requirements.txt
virtualenv:                                                                                                                                                                                                                         
  system_site_packages: true 
script: nosetests om10/test.py
